export const UPLOAD_TEXT_REQUEST = 'UPLOAD_TEXT_REQUEST';
export const UPLOAD_TEXT_SUCCESS = 'UPLOAD_TEXT_SUCCESS';
export const UPLOAD_TEXT_FAILURE = 'UPLOAD_TEXT_FAILURE';

export const UPLOAD_VIDEO_REQUEST = 'UPLOAD_VIDEO_REQUEST';
export const UPLOAD_VIDEO_SUCCESS = 'UPLOAD_VIDEO_SUCCESS';
export const UPLOAD_VIDEO_FAILURE = 'UPLOAD_VIDEO_FAILURE';

export const UPLOAD_AUDIO_REQUEST = 'UPLOAD_AUDIO_REQUEST';
export const UPLOAD_AUDIO_SUCCESS = 'UPLOAD_AUDIO_SUCCESS';
export const UPLOAD_AUDIO_FAILURE = 'UPLOAD_AUDIO_FAILURE';

export const DELETE_ALL_PDFS = 'DELETE_ALL_PDFS';

export const CLEAR_UPLOAD_ERROR = 'CLEAR_UPLOAD_ERROR';
